import { PrismaClient } from '@prisma/client';
export declare const SEED_PASSWORD_DEMO = "11111111";
export declare const SEED_PASSWORD_ADMIN = "Admin12345!";
export declare const SEED_IDS: {
    users: {
        admin: string;
        adminGmail: string;
        bah: string;
        fatou: string;
        laminSeeker: string;
        mariama: string;
        omar: string;
        aisha: string;
        ibrahim: string;
        kaddy: string;
        samba: string;
        neneh: string;
        modou: string;
        haddy: string;
        yusupha: string;
        binta: string;
        employerAtlantic: string;
        employerRiver: string;
        employerTourism: string;
        employerFinance: string;
        employerKotu: string;
        employerRetail: string;
        employerSkills: string;
        employerAgro: string;
    };
    jobs: {
        frontend: string;
        dataAnalyst: string;
        customerSupport: string;
        marketing: string;
        warehouse: string;
        backendDev: string;
        uxDesigner: string;
        hrAssistant: string;
        salesRep: string;
        tourGuide: string;
        accountant: string;
        nurse: string;
        electrician: string;
        teacher: string;
        driver: string;
        chef: string;
        socialMedia: string;
        projectManager: string;
        dataEntry: string;
        security: string;
        mobileDev: string;
        contentWriter: string;
        logistics: string;
        farmSupervisor: string;
        callCenter: string;
    };
    threads: {
        bahFrontend: string;
        fatouFrontend: string;
        bahData: string;
    };
};
export declare function runDatabaseSeed(prisma: PrismaClient): Promise<{
    users: number;
    jobs: number;
    applications: number;
    trainingCourses: number;
    notifications: number;
    chatThreads: number;
    chatMessages: number;
    locations: number;
}>;
